import streamlit as st
from feature_glossary import FEATURE_DESCRIPTIONS, SECTOR_CLUSTER_DESCRIPTIONS


def _desc(key: str) -> str:
    return FEATURE_DESCRIPTIONS[key]


def render_glossary_page():
    st.title("🔍︎ Glossary")
    st.markdown(
        "Definitions for each feature used by the forecasting model. "
        "LLM-graded features are scored 0–100 by *gemini-2.5-flash* "
        "based on the activity documents."
    )

    st.markdown("## LLM-Graded Activity Characteristics")
    st.markdown(
        "The following seven features are generated by *gemini-2.5-flash*, "
        "which reads the activity documents and assigns a score from 0 to 100."
    )

    for key in ("finance", "integratedness", "implementer_performance", "targets", "context", "risks", "complexity"):
        st.markdown(f"**`{key}`** — {_desc(key)}")

    st.markdown("## Country & Governance Context")

    for key in ("gdp_percap", "cpia_score", "governance_composite"):
        st.markdown(f"**`{key}`** — {_desc(key)}")

    st.markdown("## Region Dummy Variables")
    st.markdown(
        "One-hot encoded region of the activity, using World Bank regional definitions. "
        "An activity can span multiple regions."
    )

    for key in ("region_AFE", "region_AFW", "region_EAP", "region_ECA", "region_LAC", "region_MENA", "region_SAS"):
        st.markdown(f"**`{key}`** — {_desc(key)}")

    st.markdown("## Activity Characteristics")

    for key in ("activity_scope", "finance_is_loan", "planned_duration", "planned_expenditure", "log_planned_expenditure"):
        st.markdown(f"**`{key}`** — {_desc(key)}")

    st.markdown("## Reporting Organisation")
    st.markdown(
        "One-hot encoded indicator for the reporting organisation. "
        "The four most common organisations in the dataset are encoded."
    )

    from location_features import ORG_NAME_TO_DUMMY
    _dummy_to_org = {}
    _reference_orgs = []
    for _org, _dummies in ORG_NAME_TO_DUMMY.items():
        _active = [col for col, on in _dummies.items() if on == 1]
        if _active:
            _dummy_to_org[_active[0]] = _org
        else:
            _reference_orgs.append(_org)

    for _col in sorted(_dummy_to_org):
        st.markdown(f"**`{_col}`** — {_dummy_to_org[_col]}")
    if _reference_orgs:
        st.markdown(
            f"*{', '.join(_reference_orgs)} is the omitted reference category "
            "(all rep_org dummies 0, but included in the training data).*"
        )

    st.markdown("## Target Embedding Coordinates (UMAP)")
    st.markdown(
        "Activity objectives (*targets*) are summarised by *gemini-2.5-flash*, "
        "embedded with *gemini-embedding-001*, compressed via PCA to 50 dimensions, "
        "and then projected to 3D by UMAP. Activities with similar objectives cluster "
        "near each other in this space. The three coordinates are used directly as "
        "model features."
    )

    for key in ("umap3_x", "umap3_y", "umap3_z", "sector_distance", "country_distance"):
        st.markdown(f"**`{key}`** — {_desc(key)}")

    from model_loader import get_sector_clusters
    _clusters = get_sector_clusters()

    st.markdown("## Sector Budget Allocation Clusters")
    st.markdown(
        "Activity budgets are broken down into sub-components by *gemini-2.5-flash*. "
        f"Sub-components are embedded and clustered into {len(_clusters)} groups. Each feature "
        "reports the share of the total budget allocated to that cluster "
        "(0 if not applicable). Approximately 55% of activities have identifiable "
        "budget breakdowns."
    )

    for cluster in _clusters:
        desc = SECTOR_CLUSTER_DESCRIPTIONS.get(cluster, cluster.replace("_", " "))
        st.markdown(f"**`sector_cluster_{cluster}`** — {desc}")

    st.markdown("## Missingness Indicators")
    st.markdown(
        "Binary flags and counts recording when key features could not be computed "
        "due to missing data. These are included as model features because missingness "
        "itself can be informative about activity quality or data reporting."
    )

    for key in (
        "llm_features_missing_count", "llm_features_present_ratio",
        "governance_missing_count", "feature_completeness_ratio",
        "cpia_missing", "sector_clusters_missing", "gdp_percap_missing",
        "planned_expenditure_missing", "planned_duration_missing",
        "wgi_any_missing", "umap_missing",
    ):
        st.markdown(f"**`{key}`** — {_desc(key)}")
