import streamlit as st


def render_glossary_page():
    st.title("🔍︎ Glossary")
    st.markdown(
        "Definitions for each feature used by the forecasting model. "
        "LLM-graded features are scored 0–100 by *gemini-2.5-flash* "
        "based on the activity documents."
    )

    # ------------------------------------------------------------------ #
    # LLM-graded activity characteristics
    # ------------------------------------------------------------------ #
    st.markdown("## LLM-Graded Activity Characteristics")
    st.markdown(
        "The following seven features are generated by *gemini-2.5-flash*, "
        "which reads the activity documents and assigns a score from 0 to 100."
    )

    st.markdown("**`finance`** — How well-financed the activity is (0–100). "
                "Considers adequacy of the budget relative to planned scope and duration.")

    st.markdown("**`integratedness`** — How well the activity is integrated within "
                "the broader aid ecosystem (0–100). Higher scores indicate strong "
                "coordination with complementary programmes, government systems, and "
                "local institutions.")

    st.markdown("**`implementer_performance`** — Expected quality of the implementing "
                "organisation based on evidence in the documents (0–100).")

    st.markdown("**`targets`** — Ease and clarity of the targeted outcomes (0–100). "
                "Higher scores indicate well-defined, realistic, and measurable targets.")

    st.markdown("**`context`** — Degree of contextual challenge faced by the activity "
                "(0–100). Higher scores indicate a more favourable operating environment.")

    st.markdown("**`risks`** — Overall risk level of the activity (0–100). "
                "Higher scores indicate *lower* risk.")

    st.markdown("**`complexity`** — Technical complexity of the activity (0–100). "
                "Higher scores indicate greater complexity.")

    # ------------------------------------------------------------------ #
    # Country & governance context
    # ------------------------------------------------------------------ #
    st.markdown("## Country & Governance Context")

    st.markdown("**`gdp_percap`** — log(GDP per capita) of the country or countries "
                "where the activity takes place, weighted by the share of activity "
                "performed in each country.")

    st.markdown("**`cpia_score`** — Country Policy and Institutional Assessment score "
                "from the World Bank. Rates the quality of a country's policies and "
                "institutions on a scale of 1–6.")

    st.markdown("**`governance_composite`** — Mean of the five World Governance "
                "Indicators (WGI): control of corruption, government effectiveness, "
                "political stability, regulatory quality, and rule of law. "
                "Computed only when none of the five components are missing.")

    # ------------------------------------------------------------------ #
    # Region dummies
    # ------------------------------------------------------------------ #
    st.markdown("## Region Dummy Variables")
    st.markdown(
        "One-hot encoded region of the activity, using World Bank regional definitions. "
        "An activity can span multiple regions."
    )

    st.markdown("**`region_AFE`** — Eastern and Southern Africa")
    st.markdown("**`region_AFW`** — Western and Central Africa")
    st.markdown("**`region_EAP`** — East Asia and Pacific")
    st.markdown("**`region_ECA`** — Europe and Central Asia")
    st.markdown("**`region_LAC`** — Latin America and the Caribbean")
    st.markdown("**`region_MENA`** — Middle East and North Africa")
    st.markdown("**`region_SAS`** — South Asia")

    # ------------------------------------------------------------------ #
    # Activity characteristics
    # ------------------------------------------------------------------ #
    st.markdown("## Activity Characteristics")

    st.markdown("**`activity_scope`** — Geographic scope of the activity on a 1–7 "
                "scale: 1 = local/sub-national, 7 = global.")

    st.markdown("**`finance_is_loan`** — Binary flag (1/0) indicating whether the "
                "primary financing instrument is a loan rather than a grant.")

    st.markdown("**`planned_duration`** — Planned length of the activity in days, "
                "derived from the planned start and end dates.")

    st.markdown("**`planned_expenditure`** — Planned total disbursement in USD.")

    st.markdown("**`log_planned_expenditure`** — Natural log of planned total "
                "disbursement. This transformation reduces the influence of extreme "
                "values and is used directly in the model alongside the raw figure.")

    # ------------------------------------------------------------------ #
    # Reporting organisation
    # ------------------------------------------------------------------ #
    st.markdown("## Reporting Organisation")
    st.markdown(
        "One-hot encoded indicator for the reporting organisation. "
        "The four most common organisations in the dataset are encoded."
    )

    from location_features import ORG_NAME_TO_DUMMY
    _dummy_to_org = {}
    _reference_orgs = []
    for _org, _dummies in ORG_NAME_TO_DUMMY.items():
        _active = [col for col, on in _dummies.items() if on == 1]
        if _active:
            _dummy_to_org[_active[0]] = _org
        else:
            _reference_orgs.append(_org)

    for _col in sorted(_dummy_to_org):
        st.markdown(f"**`{_col}`** — {_dummy_to_org[_col]}")
    if _reference_orgs:
        st.markdown(
            f"*{', '.join(_reference_orgs)} is the omitted reference category "
            "(all rep_org dummies 0, but included in the training data).*"
        )

    # ------------------------------------------------------------------ #
    # UMAP embedding coordinates
    # ------------------------------------------------------------------ #
    st.markdown("## Target Embedding Coordinates (UMAP)")
    st.markdown(
        "Activity objectives (*targets*) are summarised by *gemini-2.5-flash*, "
        "embedded with *gemini-embedding-001*, compressed via PCA to 50 dimensions, "
        "and then projected to 3D by UMAP. Activities with similar objectives cluster "
        "near each other in this space. The three coordinates are used directly as "
        "model features."
    )

    st.markdown(
        "**`umap3_x`** — First UMAP dimension. Low values correspond to forestry, "
        "agriculture, water management, and natural resource objectives. High values "
        "correspond to energy-sector and financing-oriented objectives."
    )

    st.markdown(
        "**`umap3_y`** — Second UMAP dimension. Low values are associated with "
        "energy-focused activities. High values are associated with biodiversity, "
        "wastewater, and conservation objectives."
    )

    st.markdown(
        "**`umap3_z`** — Third UMAP dimension. Primarily reflects an urban–rural axis. "
        "Low values are associated with rural, wildlife, and UNDP-led activities. "
        "High values are associated with urban sanitation and wastewater objectives. "
        "This axis also weakly correlates with the number of countries (low z → fewer "
        "countries) and with how 'cookie-cutter' the activity objectives are."
    )

    st.markdown(
        "**`sector_distance`** — Distance in the UMAP embedding space between the "
        "activity and the centroid of its sector cluster. Measures how atypical the "
        "activity's objectives are relative to similar activities."
    )

    st.markdown(
        "**`country_distance`** — Distance in the UMAP embedding space between the "
        "activity and the centroid of activities in the same country. Measures how "
        "contextually unusual the activity's objectives are for that country."
    )

    # ------------------------------------------------------------------ #
    # Sector cluster features
    # ------------------------------------------------------------------ #
    from model_loader import get_sector_clusters
    _clusters = get_sector_clusters()

    st.markdown("## Sector Budget Allocation Clusters")
    st.markdown(
        "Activity budgets are broken down into sub-components by *gemini-2.5-flash*. "
        f"Sub-components are embedded and clustered into {len(_clusters)} groups. Each feature "
        "reports the share of the total budget allocated to that cluster "
        "(0 if not applicable). Approximately 55% of activities have identifiable "
        "budget breakdowns."
    )

    # Curated descriptions keyed by artifact cluster name. Names come from the
    # model artifact (get_sector_clusters) so this list can never drift; clusters
    # without a curated description fall back to a humanised label.
    _cluster_descriptions = {
        "increased_food_production": "Interventions targeting increases in agricultural output and food security.",
        "Project_Management": "Budget allocated to project management, administration, and oversight.",
        "more_people_with_drinking_water_services": "Investments in drinking water access and supply infrastructure.",
        "reduced_CO2_emissions": "Activities targeting greenhouse gas / CO₂ emission reductions.",
        "Improved_transport_infrastructure": "Road, rail, port, or other transport infrastructure improvements.",
        "Contingencies": "Contingency reserves built into the budget.",
        "Institutional_capacity_building": "Strengthening the capacity of government or partner institutions.",
        "Financing_charges": "General financing charges and fees.",
        "Urban_flood_protection": "Infrastructure and measures for urban flood risk reduction.",
        "Climate_adaptation": "Activities building resilience to climate change impacts.",
        "Capacity_Building_and_Technical_Assistance": "Capacity development and technical assistance for institutions.",
        "increased_managed_forest_land": "Increasing the area of sustainably managed or protected forest land.",
        "Green_growth_initiatives": "Programmes promoting environmentally sustainable economic growth.",
        "Road_safety_improvements": "Measures reducing road traffic injuries and improving road safety.",
        "reduced_PM2.5_air_pollution": "Activities targeting reductions in fine-particulate (PM2.5) air pollution.",
        "Land_acquisition_and_resettlement": "Costs of land acquisition and resettlement of affected populations.",
    }

    for cluster in _clusters:
        desc = _cluster_descriptions.get(cluster, cluster.replace("_", " "))
        st.markdown(f"**`sector_cluster_{cluster}`** — {desc}")

    # ------------------------------------------------------------------ #
    # Missingness indicators
    # ------------------------------------------------------------------ #
    st.markdown("## Missingness Indicators")
    st.markdown(
        "Binary flags and counts recording when key features could not be computed "
        "due to missing data. These are included as model features because missingness "
        "itself can be informative about activity quality or data reporting."
    )

    st.markdown("**`llm_features_missing_count`** — Number of the seven LLM-graded "
                "features (finance, integratedness, etc.) that are absent.")

    st.markdown("**`llm_features_present_ratio`** — Fraction of the seven LLM-graded "
                "features that are present (1 − missing_count / 7).")

    st.markdown("**`governance_missing_count`** — Number of the five WGI governance "
                "indicators that are missing for the activity's country.")

    st.markdown("**`feature_completeness_ratio`** — Overall fraction of model features "
                "that have non-missing values for this activity.")

    st.markdown("**`cpia_missing`** — 1 if the CPIA score is unavailable, 0 otherwise.")

    st.markdown("**`sector_clusters_missing`** — 1 if no budget breakdown could be "
                "identified for sector cluster assignment, 0 otherwise.")

    st.markdown("**`gdp_percap_missing`** — 1 if GDP per capita data is unavailable "
                "for the activity's country, 0 otherwise.")

    st.markdown("**`planned_expenditure_missing`** — 1 if planned total disbursement "
                "is not reported, 0 otherwise.")

    st.markdown("**`planned_duration_missing`** — 1 if planned start or end date is "
                "missing (so duration cannot be computed), 0 otherwise.")

    st.markdown("**`wgi_any_missing`** — 1 if any of the five WGI governance indicators "
                "are missing, 0 otherwise.")

    st.markdown("**`umap_missing`** — 1 if UMAP coordinates could not be computed "
                "(e.g. targets text was absent), 0 otherwise.")
